db.driverClassName=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/davidwang456?characterEncoding=UTF-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
db.username=root
db.password=wangwei456
hibernate.sqldialect=org.hibernate.dialect.MySQLDialect
hibernate.showsql=true